### ISSUE TITLE
In DAG module, Graph should not be able to add itself as Node

### ISSUE THREAD

**Issue by Arpan3323** [nndeploy/nndeploy#116]
### Describe the bug
added the test below and it passes. Ideally, `Graph` should not be able to add *itself* as a `Node`. This can lead to undefined behavior when processing `Node`s of such a `Graph`. 
```C++
TEST_F(GraphTest, GraphWithNodeAsItself) {
    auto inputs = std::vector<Edge *>();
    auto outputs = std::vector<Edge *>();
    auto edge_in =  std::make_unique<Edge>("edge_in");
    auto edge_out =  std::make_unique<Edge>("edge_out");
    inputs.emplace_back(edge_in.get());
    outputs.emplace_back(edge_out.get());
    auto graph = ConstructGraphWithVecArgs("@@!!##$$", inputs, outputs);
    ASSERT_TRUE(graph->addNode(graph.get()) == kStatusCodeOk); //this can lead to problems
}
```

### Potential fix
A mechanism within the `nndeploy::dag::Graph` to prevent this. Perhaps, something among lines of `if (node == this) return nullptr` in `nndeploy::base::Status nndeploy::dag::Graph::addNode(Node *node, bool is_external)` and `*nndeploy::dag::Graph::createInfer(...)`

**Comment by Alwaysssssss** [comment]
Yes, this kind of situation should be prohibited.
