### ISSUE TITLE
Graph constructed with same input and output Edge stores the duplicate Edge

### ISSUE THREAD

**Issue by Arpan3323** [nndeploy/nndeploy#117]
### Describe the issue
The line `EXPECT_FALSE(graph->getAllOutput()[0] == edge_in.get());` causes the test to fail. I expected that if we called the constructor with duplicate input and output, `std::vector<Edge *> outputs_` would be empty, since output Edge is processed after input and a duplicate should be detected because of #113  but that is not the case.
```C++
//This test fails, there may be chance of potential optimizations
TEST_F(GraphTest, GraphWithDuplicateOutputEdge) {
    auto edge_in =  std::make_unique<Edge>("edge_in");
    auto graph = ConstructGraph("3.141@@!!", edge_in.get(), edge_in.get());
    EXPECT_FALSE(graph->getConstructed()); //is false
    EXPECT_FALSE(graph->getAllOutput()[0] == edge_in.get()); // this should false; somehow getAllOutput().size() != 0
    EXPECT_TRUE(graph->getAllInput()[0] == edge_in.get()); //is true 
}
```

**Comment by Alwaysssssss** [comment]
Your test expectation is correct and it should be as you expected. I think currently the Graph should not be able to support the situation where both the input and the output are the same edge.

**Comment by Arpan3323** [comment]
The reason this test was failing is because `Node` constructor is called in the `Graph` constructor's initialization list. To prevent this, I have added [some checks](https://github.com/nndeploy/nndeploy/blob/main/framework/source/nndeploy/dag/node.cc#L7-L37) in the constructors of `Node`. I have tested these checks and they work fine but there is clearly some overhead introduced. If you think these are fine, I can go ahead and close this issue but would be more than happy to hear any suggestions that you may have.

**Comment by Alwaysssssss** [comment]
Sorry for the late reply to this issue. Adding extra checks in the constructor doesn't bring much overhead, but it can make our code more robust. I'm quite happy to accept this modification.
